language: ruby
rvm: 2.0.0
before_script:
- '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup'
script: rake build
after_success:
- '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish'

env:
  global:
    - GIT_COMMITTER_NAME="kyaido"
    - GIT_COMMITTER_EMAIL="kamehameha1985@gmail.com"
    - GIT_AUTHOR_NAME="kyaido"
    - GIT_AUTHOR_EMAIL="kamehameha1985@gmail.com"
    - secure: "PDsGp0UWu4OtqvbMaMsEGlXU0PU5/HTQ87b8EnpacF3zSgYCBh80uaL2148+bfYGdJ5T3vtMBIqIYKNPfvtcu+Gnn8h7teRlskr8PQbWyIYqSL/o/LMgyMHp5xkXVq42oSzZu6a1GNxAmoKtVjWoQQ+8qMSx4xyCQ78+q12mdZE="